### ISSUE TITLE
Feature request: support YAML metadata for Debian platform

### ISSUE THREAD

**Issue by kprasadvnsi** [bilelmoussaoui/appstream#11]
I am writing an App store application in Rust. It so happened that this application must run on Debian that only provides YAML metadata.

**Comment by bilelmoussaoui** [comment]
Shouldn't be too hard to adapt the exiting code to make use of that, most of types implement `Deserialize` already and that is all you need for YAML support but then you might need to switch some of those to be manually implemented I guess.

I would start adding some very basic tests on top of the xml/json ones we have and adapt the code while keeping the other tests running.

Note I have no interest in adding yaml support in the upcoming future, if someone does the work I would happily accept patches

**Comment by bilelmoussaoui** [comment]
Going to close this as it is not in the scope of the project, if someone has interest in supporting the yaml format, feel free to submit a patch.
