### ISSUE TITLE
try_from fails on empty translations

### ISSUE THREAD

**Issue by A6GibKm** [bilelmoussaoui/appstream#5]
Any file which includes
```xml
<translation></translation>
```
or
```xml
<translation/>
```
Will result in an error when loading as
```rust
        let element = xmltree::Element::parse(data).unwrap();
        let appdata = Component::try_from(&element).unwrap();
```

For some reason that it is beyond the grasp of the author, this is a very common practice in metainfo files.

**Comment by bilelmoussaoui** [comment]
I just gave this a thought and i don't think it makes sense to unwrap while parsing a random non validated appstream file. Instead you should retrieve the error and display it to the user if needed.  
```rust
let element = xmltree::Element::parse(data).unwrap();
match Component::try_from(&element) {
   Ok(appdata) => println!("{:#?}", appdata),
   Err(err) => show_error(err),
};
``` 
Closing
